### ISSUE TITLE
url_for/link_to helpers

### ISSUE THREAD

**Issue by moonglum** [soveran/syro#18]
This is something I was thinking about over the weekend, and wanted to get your (you being creators and users of Syro) opinion about it:

Let's say I want to create a helper that will create links to certain resources (e.g. `url_for @user` will return `"/users/14"`). In Syro there is no concept of a resource, there is just matching. Therefore it is not possible to create helpers like that. Similar things are true and have been discussed for Cuba in regards to providing a `rake routes` task (soveran/cuba#65).

Syro builds routing trees. When I think about trees, I also think about tree traversals. But I think traversing the Syro routing tree is not possible as it is dynamic and build with ruby blocks. Or am I wrong in that?

How are you handling URLs in your application? Are you just hard coding them? When you change the structure of your URLs, do you go through all views/templates and replace them?

**Comment by soveran** [comment]
I hardcode the URLs and I rarely have to replace them, but when I do it's mostly a find and replace operation. Maybe the helper can be useful even if you can't have the routes available, as it will allow you to standardise the naming convention.

If you want to investigate how to traverse the tree, here's an idea: imagine you have a custom `Deck` called `WalkerDeck`, and it's defined as follows:

``` ruby
$indent = 0

class WalkerDeck < Syro::Deck
  def debug(arg)
    printf("%s%s\n", "-" * $indent, arg)

    $indent += 1
    yield
    $indent -= 1
  end

  def default
    debug("default") { yield }
  end

  def get
    debug("get") { yield }
  end

  def post
    debug("post") { yield }
  end

  def on(arg)
    debug(sprintf("on(%p)", arg)) { yield }
  end
end
```

It's incomplete, as you would have to redefine all the matchers from Syro. Take this only as an example to illustrate the idea.

You can now use `WalkerDeck` in place of your normal Deck, and it will print the routes. You can redefine what `debug` does to better suit your needs. For example, you can redefine it to create a hash with the routes, or you can print them differently. In this example, it just prints the tree.

Here's how you would use it:

``` ruby
walker = Syro.new(WalkerDeck) {
  on("foo") {
    on("bar") {
      on("baz") {
        get {
          res.write "GET /foo/bar/baz"
        }
      }
    }
  }

  on(true) {
    on(false) {
      get {
        res.write "GET /true/false"
      }
    }

    on(true) {
      post {
        res.write "POST /true/true"
      }
    }
  }

  default {
    res.write "Default"
  }
}
```

When you call the `walker` app, this will be printed:

```
on("foo")
-on("bar")
--on("baz")
---get
on(true)
-on(false)
--get
-on(true)
--post
default
```

Note that this is just a quick version and I didn't look at ways to make it better!

**Comment by moonglum** [comment]
> I hardcode the URLs and I rarely have to replace them, but when I do it's mostly a find and replace operation. Maybe the helper can be useful even if you can't have the routes available, as it will allow you to standardise the naming convention.

Thanks for sharing! I guess that's a good way to do it, if and only if you are testing your web app as an hypermedia API aka. not hard coding links in your tests, but instead "clicking" on them (like you do with Capybara for example). As I personally follow this philosophy, I think that works as you will find dead or wrong links in your tests this way.

**Walker:**

Thank you :smile: Thought about something similar "What if I overwrite the on matcher... hm". That's a good solution for that. It has two problems though:
1. The walker deck has to be kept up to date with the deck your actually using, so that you react to all additional matchers you might have.
2. You somehow need to run your application first with the walker (to build up the routing tree), and then the regular deck (to run your application).

The solution to 1 is probably discipline. No way around it.

The solution to 2 is maybe to provide a second method similar to Rack's `run` method. So your app would end with:

``` ruby
# ...

routing_info = routing_info_for App # this would need to inject a different deck somehow
run App
```

I also wanted to check, what the Roda folks are doing and found [this](https://github.com/jeremyevans/roda-route_list). But I don't like it so much, as you then are using your comments to generate code...

**Comment by soveran** [comment]
I was thinking about it more like a debugging tool, never to be run in production.

About the first point, maybe you can get almost there with a standard `Walker` that wraps your application deck, checks what instance methods were defined in it and redefines them in order to call the debug method. But maybe this is the kind of problem that is better to avoid, as the perfect solution may create a disproportionate amount of complexity.

**Comment by moonglum** [comment]
Ok, understood :smile: What I imagined worked more like this:

``` ruby
app = Syro.new {
  path_name :root
  get {
    res.write "GET /"
  }

  on("users") {
    on(:id) {
      path_name :user, :id # it could even take the `:id` from the matchers...

      @user = User[inbox[:id]]

      get {
        res.write "GET /users/42"
      }

      delete {
        res.write "PUT /users/42"
      }
  }
}
```

Now you could do the following:

``` ruby
assert_equal '/', url_for(:root)
assert_equal '/users/11', url_for(:user, id: 11)
```

So this would require some data structure storing this information that the `url_for` could use.

**Comment by frodsan** [comment]
@moonglum Do you remember the talk about rubocop's parser in Euruko? Do you think we can use it to generate a list of routes?

**Comment by moonglum** [comment]
@frodsan I thought about something similar. On the other hand it seems a little odd to make a static code analysis to get a routing table... I want to try it though :smiley:

**Comment by soveran** [comment]
We can now point people to [Shigeru][shigeru], a routing library agnostic uri_for helper :-)

[shigeru]: https://github.com/moonglum/shigeru

**Comment by moonglum** [comment]
Yep 😸
