### ISSUE TITLE
Nested Script Name & Path Info

### ISSUE THREAD

**Issue by evanleck** [soveran/syro#28]
Hello! I've been using Syro for a bit now on a few projects and started noticing something weird when composing multiple apps together using `run`. Namely, it appears that the `req.script_name` gets truncated as nesting increases.

For example, take this config.ru:

```ruby
require 'syro'

Path = Syro.new do
  get do
    res.text req.path
  end
end

Script = Syro.new do
  on('path') do
    run Path
  end
end

App = Syro.new do
  on('script') do
    run Script
  end
end

run App
```

A `GET /script/path` will return just `/path` in the body but I would expect it to return the entire path part of the request e.g. `/script/path`. `Rack::Request#path` returns `script_name + path_info`, but it appears that the `script_name` isn't propagating down.

Is this expected behavior? If not, I imagine it has something to do with the [juggling happening here](https://github.com/soveran/syro/blob/84ac6de22ad5c261b41d3715ae16f3da51feea71/lib/syro.rb#L279-L280).

Thanks for your time!

**Comment by soveran** [comment]
Hey @evanleck, glad you are using Syro :-)

Thanks for reporting this issue. I thought it was the intended behavior, but now I see how it may be wrong. The original idea was for each mounted app to be unaware of where it had been mounted, but it's true that the `SCRIPT_NAME` should be propagated. I think we can change the line to be something like this:

```ruby
env[Rack::SCRIPT_NAME] = script + @syro_path.prev
```

I will try it to see if there's something else we are not taking into account. Can you try it and let me know if it behaves the way you expected it to behave?

**Comment by evanleck** [comment]
Using and loving it :)

That change makes everything behave as I would expect. Using the same example code, `GET /script/path` writes `/script/path` to the body.

**Comment by soveran** [comment]
Excellent! I just pushed version 3.1.1 which includes that change :-)

Thanks!

**Comment by evanleck** [comment]
Awesome, thank you!
