### ISSUE TITLE
Can't compose Syro apps with Rack apps

### ISSUE THREAD

**Issue by djanowski** [soveran/syro#6]
Because `Syro#run` assumes the argument is another Syro app, it passes the inbox, raising an error on regular Rack apps.

The use case is using Syro as the main entry point in an application to dispatch different paths to different sub-apps. These sub-apps could be Cuba, or even another `Rack::Builder` instance (eg because Syro doesn't support middleware).

Example that breaks:

``` ruby
require "syro"

Other = -> env { [200, {"Content-Type" => "text/html"}, [""]] }

App = Syro.new do
  get {
    run(Other)
  }
end

App.call(Rack::MockRequest.env_for("/"))

# wrong number of arguments (2 for 1) (ArgumentError)
```

So the options I see are:
1. Check the arity of `app.call` and decide whether to pass inbox or not.
2. Check if `app` is a Syro instance and decide whether to pass inbox or not.
3. Have a separate method for composing with Rack apps.
4. Do nothing. If you want to use a router, use `Rack::Builder#map`.
5. **Update**: As suggested by @tizoc, we could move the inbox to the Rack environment. After all, it's context associated with the request. And as he pointed out, you'd lose the inbox if you do Syro → Rack → Syro.

~~Option 3 sounds simple enough to me, allows the desired behavior and reveals intent. If we go for this one, then we can discuss whether `run` is the method that composes Syro or Rack apps (in my opinion, `run` is a standard for Rack apps, so we can find another name for when you compose Syro apps, like `dispatch` or `delegate`).~~  **Update**: After @tizoc's suggestion, I'm leaning towards option 5.

**Comment by djanowski** [comment]
Updated issue description with @tizoc's suggestion of making the inbox part of the Rack environment.

**Comment by foca** [comment]
:+1: to using `env` for this.

**Comment by soveran** [comment]
Maybe the right approach for now is to rename `run` to `mount` or something like that, to make it clear that it's not tied to Rack's API in that regard.

We can explore the idea of using `env` for the inbox, but at first I think it shouldn't be desirable. In fact, I'm thinking more about decoupling it from Rack than otherwise. I'm a bit skeptical of the "middleware" pattern lately, as it looks very costly. We should definitely discuss this at length.

For now, I think using `Rack::Builder` is the way to go if there's a need to add middlewares to different apps.

About the new name: what do you guys think? Is `mount` preferable? Other ideas?

**Comment by tizoc** [comment]
Maybe I misunderstanding the inbox, but it seems to me like it is meant to provide temporary storage to be shared across components, and its lifecycle is attached to the one of the request->response lifecycle, just like the env. Thats why I think it makes sense to store it on the env (`env['syro.inbox']` for example), I was not even thinking about "middlewares" (a concept I don't find that convincing either).

re: name ideas:
- `yield` (but it is taken by the language)
- `forward`
- `delegate`
- `transfer`

**Comment by soveran** [comment]
@djanowski @foca @tizoc What do you think about the commit https://github.com/soveran/syro/commit/4edf5b15576bfc1c17395a099a1f786b33c5f3d5?

If you are all +1, we can release it.

**Comment by djanowski** [comment]
+1!

**Comment by soveran** [comment]
Released in 0.0.7.

**Comment by foca** [comment]
:tada: :heart: :sparkles:

**Comment by tizoc** [comment]
:+1:
